Fix deprecation
paviliondev/discourse-ratings pull request #56
Opened 2023-02-13 18:45 UTC by jumagura

2023-02-14 13:07 UTC, merefield commented
Looks good.  However, is it worth adding front end tests just on this scope as a start to incrementally increasing coverage?

2024-02-23 15:33 UTC, jumagura commented
HI @merefield just updating this PR for bootbox deprecation. I will create another PR for frontend tests and CI. if that is okay with you

2024-02-23 16:46 UTC, merefield commented
Ooh thanks for this @jumagura.  If you don't mind I will review on Monday?

2024-02-27 10:36 UTC, merefield requested changes

2024-02-28 11:47 UTC, merefield requested changes

2024-02-28 11:47 UTC, merefield commented on assets/javascripts/discourse/templates/components/rating-migrate.hbs
> +  @action={{action "migrate"}}
This should reference the action using `this` not using a string.

2024-02-28 11:47 UTC, merefield commented on assets/javascripts/discourse/templates/components/rating-destroy.hbs
> +  @action={{action "destroyRatings"}}
This should reference the action using `this` not using a string.

2024-02-28 14:52 UTC, merefield approved these changes

2024-02-28 14:53 UTC, merged

2024-02-28 15:03 UTC, merefield commented
thanks @jumagura ! 👍